<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>API_Rodoviaria</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.31" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.31" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.31">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Application\DTO%27s\Requisicao\ViagemRequisicaoDTO\" />
    <Folder Include="Application\DTO%27s\Requisicao\RotaRequisicaoDTO\" />
    <Folder Include="Application\DTO%27s\Requisicao\UsuarioRequisicaoDTO\" />
    <Folder Include="Application\DTO%27s\Resposta\MotoristaRespostaDTO\" />
    <Folder Include="Application\DTO%27s\Resposta\CadeiraRespostaDTO\" />
    <Folder Include="Application\DTO%27s\Resposta\ReservaCadeiraRespostaDTO\" />
    <Folder Include="Application\DTO%27s\Resposta\OnibusRespostaDTO\" />
    <Folder Include="Application\DTO%27s\Resposta\ReservaRespostaDTO\" />
    <Folder Include="Application\DTO%27s\Resposta\RotaRespostaDTO\" />
    <Folder Include="Application\DTO%27s\Resposta\UsuarioRespostaDTO\" />
    <Folder Include="Application\DTO%27s\Resposta\ViagemRespostaDTO\" />
    <Folder Include="Application\UseCase\CadeiraCasosDeUso\CriarCadeira\" />
    <Folder Include="Application\UseCase\MotoristaCasosDeUso\CriarMotorista\" />
    <Folder Include="Application\UseCase\Onibus\CriarOnibus\" />
    <Folder Include="Application\UseCase\ReservaCadeiraCasosDeUso\CriarReservaCadeira\" />
    <Folder Include="Application\UseCase\ReservaCasosDeUso\CriarReserva\" />
    <Folder Include="Application\UseCase\RotaCasoDeUso\CriarRota\" />
    <Folder Include="Application\UseCase\UsuarioCasosDeUso\CriarUsuario\" />
    <Folder Include="Application\UseCase\UsuarioCasosDeUso\Login\" />
    <Folder Include="Application\UseCase\VIagemCasosDeUso\CriarViagem\" />
    <Folder Include="Domain\Interfaces\" />
    <Folder Include="Domain\Enums\" />
    <Folder Include="Infrastructure\DataAccess\Repository\RepositorioReservaCadeira\" />
    <Folder Include="Infrastructure\DataAccess\Repository\RepositorioCadeira\" />
    <Folder Include="Infrastructure\DataAccess\Repository\RepositorioRota\" />
    <Folder Include="Infrastructure\DataAccess\Repository\RepositorioReserva\" />
    <Folder Include="Infrastructure\DataAccess\Repository\RepositorioViagem\" />
    <Folder Include="Infrastructure\DataAccess\Repository\RepositorioOnibus\" />
    <Folder Include="Infrastructure\DataAccess\Repository\RepositorioMotorista\" />
    <Folder Include="Infrastructure\DataAccess\Repository\RepositorioUsuario\" />
    <Folder Include="Infrastructure\Services\" />
  </ItemGroup>

</Project>
