// <auto-generated />
using System;
using API_Rodoviaria.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API_Rodoviaria.Migrations
{
    [DbContext(typeof(RodoviariaDbContext))]
    [Migration("20261001182329_Rodoviado")]
    partial class Rodoviado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API_Rodoviaria.Domain.Models.Cadeira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FkOnibus")
                        .HasColumnType("integer");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FkOnibus", "Numero")
                        .IsUnique();

                    b.ToTable("Cadeira", (string)null);
                });

            modelBuilder.Entity("API_Rodoviaria.Domain.Models.Motorista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Cnh")
                        .IsUnique();

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Motorista", (string)null);
                });

            modelBuilder.Entity("API_Rodoviaria.Domain.Models.Onibus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacidadeTotal")
                        .HasColumnType("integer");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Onibus", (string)null);
                });

            modelBuilder.Entity("API_Rodoviaria.Domain.Models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Cargo")
                        .IsUnique();

                    b.ToTable("Perfil", (string)null);
                });

            modelBuilder.Entity("API_Rodoviaria.Domain.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FkUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("FkViagem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FkUsuario");

                    b.HasIndex("FkViagem");

                    b.ToTable("Reserva", (string)null);
                });

            modelBuilder.Entity("API_Rodoviaria.Domain.Models.ReservaCadeira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FkCadeira")
                        .HasColumnType("integer");

                    b.Property<int>("FkReserva")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FkCadeira");

                    b.HasIndex("FkReserva", "FkCadeira")
                        .IsUnique();

                    b.ToTable("ReservaCadeira", (string)null);
                });

            modelBuilder.Entity("API_Rodoviaria.Domain.Models.Rota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EnderecoFim")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EnderecoInicio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Rota", (string)null);
                });

            modelBuilder.Entity("API_Rodoviaria.Domain.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("FkPerfil")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FkPerfil");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("API_Rodoviaria.Domain.Models.Viagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataChegada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataSaida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FkMotorista")
                        .HasColumnType("integer");

                    b.Property<int>("FkOnibus")
                        .HasColumnType("integer");

                    b.Property<int>("FkRota")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FkMotorista");

                    b.HasIndex("FkOnibus");

                    b.HasIndex("FkRota");

                    b.ToTable("Viagem", (string)null);
                });

            modelBuilder.Entity("API_Rodoviaria.Domain.Models.Cadeira", b =>
                {
                    b.HasOne("API_Rodoviaria.Domain.Models.Onibus", "Onibus")
                        .WithMany("Cadeiras")
                        .HasForeignKey("FkOnibus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Onibus");
                });

            modelBuilder.Entity("API_Rodoviaria.Domain.Models.Reserva", b =>
                {
                    b.HasOne("API_Rodoviaria.Domain.Models.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("FkUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_Rodoviaria.Domain.Models.Viagem", "Viagem")
                        .WithMany("Reservas")
                        .HasForeignKey("FkViagem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("API_Rodoviaria.Domain.Models.ReservaCadeira", b =>
                {
                    b.HasOne("API_Rodoviaria.Domain.Models.Cadeira", "Cadeira")
                        .WithMany("ReservaCadeira")
                        .HasForeignKey("FkCadeira")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_Rodoviaria.Domain.Models.Reserva", "Reserva")
                        .WithMany("ReservaCadeiras")
                        .HasForeignKey("FkReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cadeira");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("API_Rodoviaria.Domain.Models.Usuario", b =>
                {
                    b.HasOne("API_Rodoviaria.Domain.Models.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("FkPerfil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("API_Rodoviaria.Domain.Models.Viagem", b =>
                {
                    b.HasOne("API_Rodoviaria.Domain.Models.Motorista", "Motorista")
                        .WithMany("Viagens")
                        .HasForeignKey("FkMotorista")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_Rodoviaria.Domain.Models.Onibus", "Onibus")
                        .WithMany("Viagens")
                        .HasForeignKey("FkOnibus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_Rodoviaria.Domain.Models.Rota", "Rota")
                        .WithMany("Viagens")
                        .HasForeignKey("FkRota")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Motorista");

                    b.Navigation("Onibus");

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("API_Rodoviaria.Domain.Models.Cadeira", b =>
                {
                    b.Navigation("ReservaCadeira");
                });

            modelBuilder.Entity("API_Rodoviaria.Domain.Models.Motorista", b =>
                {
                    b.Navigation("Viagens");
                });

            modelBuilder.Entity("API_Rodoviaria.Domain.Models.Onibus", b =>
                {
                    b.Navigation("Cadeiras");

                    b.Navigation("Viagens");
                });

            modelBuilder.Entity("API_Rodoviaria.Domain.Models.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("API_Rodoviaria.Domain.Models.Reserva", b =>
                {
                    b.Navigation("ReservaCadeiras");
                });

            modelBuilder.Entity("API_Rodoviaria.Domain.Models.Rota", b =>
                {
                    b.Navigation("Viagens");
                });

            modelBuilder.Entity("API_Rodoviaria.Domain.Models.Usuario", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("API_Rodoviaria.Domain.Models.Viagem", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
